config/routes.rb
Rails.application.routes.draw do
  resources :images do
    collection do
      get 'search'
      get 'unknown' => 'images#unknown'
      get 'random.jpg' => 'images#random', as: :random
      get 'autocomplete'
      get 'add'
      post 'add'
    end
    
    member do
      post 'publish'
      post 'klass'
    end
  end

  get '/admin' => 'application#admin'

  root to: "images#search"
end

app/models/image.rb
class Image < ActiveRecord::Base

  has_many :image_ratings

  validates :link, uniqueness: true, presence: true, format: { with: /https?:\/\/[\S]+/ }
  validates :text, uniqueness: { case_sensitive: false }, presence: true, length: { maximum: 400 }
  validate :check_image

  scope :published, -> { where(published: true) }
  scope :unpublished, -> { where(published: false) }

  def check_image
    begin
      img = Dragonfly.app.fetch_url(self.link)
      ext, width, height = img.ext, img.width, img.height
      self.sha = Digest::SHA1.hexdigest(img.data)
    rescue
      errors.add(:link, "Не получается найти изображение по ссылке =(")
    else
      errors.add(:link, "Нельзя загружать изображение как Документ вконтакте.")  if link.index("/docs/")
      errors.add(:link, "Изображение слишком большое")  if width > 1000 || height > 600
      errors.add(:link, "Такое изображение уже присутствует")  if Image.where(sha: self.sha).where.not(id: id).any?
    end
  end

  def klass(ip)
    image_rating = self.image_ratings.find_or_initialize_by(ip: ip)
    if image_rating.id?
      self
    else
      self.update_attribute(:rating, rating+1)
      image_rating.save
    end
  end

  def voted?(ip)
    image_ratings.any? {|e| e.ip == ip }
  end

  class << self
    def add_images(text, ip)
      result = { i: 0, not_added: [] }
      text.each_line do |l|
        next  unless i_can_haz_link?(l)
        link = l.split.first
        text = l[/\s(.+)/].strip
        image = self.new(link: link, text: text, added_by: ip, published: true)
        image.save ? result[:i] += 1 : result[:not_added] << image
      end
      result
    end

    def for_autocomplete(term)
      self.published.where("text ILIKE ?", "%#{term}%").limit(10).map(&:text)
    end
  end

  private

  def i_can_haz_link?(str)
    str =~ /^http\S+\s+.+$/
  end
end

app/models/image_rating.rb
class ImageRating < ActiveRecord::Base
  belongs_to :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :admin?

  def admin
    if params[:key] == ENV["admin_key"]
      session[:key] = ENV["admin_key"]
      flash[:notice] = "хахахахах такс такс такс што тут у нас админы админы админы хахахах наканецта"
    end
    redirect_to search_images_path
  end

  private

  def admin?
    ENV["admin_key"].present? && session[:key] == ENV["admin_key"]
  end
end

app/controllers/images_controller.rb
require 'open-uri'
class ImagesController < ApplicationController
  before_action :allow_cross_domain_requests, only: [:index, :search, :autocomplete]
  before_action :set_image, only: [:show, :edit, :update, :destroy, :publish, :klass]
  before_action :check_permissions, only: [:add, :edit, :update, :destroy, :publish]

  def index
    per_page = params[:per].to_i > 0 ? params[:per] : 20
    @images = build_images_relation.includes(:image_ratings).page(params[:page]).per(per_page)
  end

  def random
    image_url = Image.published.order("RANDOM()").first.link

    response.headers['Cache-Control'] = "public, max-age=#{3.hours.to_i}"
    response.headers['Content-Type'] = 'image/jpeg'
    response.headers['Content-Disposition'] = 'inline'
    render :text => open(image_url, "rb").read
  end

  def unknown
  end

  def show
  end

  def search
    @images = images_for_output
  end

  def autocomplete
    respond_to do |format|
      format.html
      format.json { render json: Image.for_autocomplete(params[:term]) }
    end
  end

  def new
    @image = Image.new
  end

  def add
    if request.post?
      @result = Image.add_images(params[:image][:text], request.remote_ip)
      flash[:notice] = "Добавлено #{@result[:i]} картинок"
    end
  end

  def edit
  end

  def create
    @image = Image.new(image_params)
    @image.published = admin?
    @image.added_by = request.remote_ip

    respond_to do |format|
      if @image.save
        @message = admin? ? "Картиночка добавлена))0" : 'Принято на рассмотрение))000'
        format.html { redirect_to @image, notice: @message }
        format.js
      else
        format.html { render :new }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Картиночка изменена))00' }
        format.js
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Картиночка удалена))000' }
      format.js
    end
  end

  def publish
    @image.update_attributes(published: true, created_at: Time.now)

    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Картиночка одобрена))000' }
      format.js
    end
  end

  def klass
    @image.klass(request.remote_ip)  if image.published?

    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Класс!' }
      format.js
    end
  end

  private
    def set_image
      @image = Image.find(params[:id])
    end

    def check_permissions
      unless admin?
        flash[:alert] = "ОЗАЙБЫРГЕН ПИЗДА"
        redirect_to :back
      end
    end

    def allow_cross_domain_requests
      response.headers['Access-Control-Allow-Origin'] = '*'
    end

    def image_params
      params.require(:image).permit(:link, :text)
    end

    def images_for_output
      @random = Image.published.order("RANDOM()").limit(2).load
      params[:image].try(:[],:text) ? Image.where("text ILIKE ?", "%#{params[:image][:text]}%").limit(5).all : [@random.first]
    end

    def build_images_relation
      images = admin? ? Image : Image.published
      images = params[:order] == "rating" ? images.order(rating: :desc) : images.order(id: :desc)
      images = Image.unpublished.order(id: :asc)  if admin? && params[:published]
      images
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def css_nav_item(action_name)
    "active"  if controller.action_name == action_name
  end

  def title_for_output
    content_for?(:title) ? yield(:title) : "Обман, чтобы набрать классы"
  end

  def image_for_output(image)
    image_tag(image.link, alt: image.text)
  end

  def klass_button(image)
    options = { class: "klass-button btn btn-sm", method: :post, remote: true, disabled: image.voted?(request.remote_ip) }
    link_to klass_image_path(image), options do
      content_tag(:i, nil, class: "klass-icon") + " Класс! " +
      (image.rating.to_s  if image.rating > 0)
    end
  end

  def menu_item(css_class, link)
    content_tag(:li, link, class: css_nav_item(css_class))
  end

  def footer_content
    author = link_to("Vizakenjack", "http://vzkj.ru", target: "_blank")
    vk_group = link_to("Филиалом Одноклассников", "http://vk.com/ok_filial", target: "_blank")
    github = link_to("Исходный код", "https://github.com/Vizakenjack/ok", target: "_blank")
    "Сделал #{author} | Вдохновлен #{vk_group} | #{github}".html_safe
  end
end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
  ALERT_TYPES = [:error, :info, :success, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      next if message.blank?
      
      type = :success if type == 'notice'
      type = :danger   if type == 'alert'
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg.to_s.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end

  def glyph(name, *classes)
    css_class = "glyphicon glyphicon-#{name}"
    css_class << " " + classes.map { |e| e }.join(" ")  if classes.present?
    content_tag :i, nil, :class => css_class
  end

end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.slim
.image.cnt
  = image_tag (@image.try(:link) || ""), class: "image-preview"
= simple_form_for @image, remote: true do |f|
  = f.input :link, label: false, placeholder: "Ссылка на изображение", input_html: { class: "input-lg" }
  = f.input :text, label: false, placeholder: "Полный текст изображения", input_html: { class: "input-lg" }
  .col-xs-offset-5 = f.button :submit, 'Добавить', class: "btn btn-lg", "data-disable-with" => "Добавление..."

app/views/images/_images_search.html.slim
- if @images
  - @images.each do |image|
    .image-content
      = link_to image_for_output(image), search_images_path, remote: true, class: "image"
      br
      p
        span.gray.copy data-clipboard-text==image.link = image.link
        span.pull-right data-image-id==image.id
          = klass_button(image)
      - if admin?
        br
        .admin-panel
          p.btn-group
            = link_to 'Изменить', edit_image_path(image), class: "btn btn-xs"
            = link_to 'Удалить', image, method: :delete, class: "btn btn-xs"

app/views/images/_images_table.html.slim
table#images-table.table
  tbody
    - images.each do |image|
      tr.image-row data-id==image.id
        td.image-cell 
          = image_tag image.link
          - unless image.published
            br
            small.gray = image.text
        td.middle
          span data-image-id==image.id
            = klass_button(image)
          - if admin?
            .cnt = image.added_by

        - if admin?
          td
            p = link_to 'Изменить', edit_image_path(image), class: "btn btn-xs"
            p = link_to 'Удалить', image, method: :delete, class: "btn btn-xs", remote: true, "data-confirm" => "Are you serious with it?"
            - unless image.published
              p = link_to 'Одобрить', publish_image_path(image), method: :post, class: "btn btn-xs btn-approve", remote: true



.cnt
  = paginate images, remote: true, params: { published: params[:published] } 

app/views/images/add.html.slim
- if @result.try(:[], :not_added)
  h3 Не удалось добавить:
  - @result[:not_added].each do |image|
    div 
      = image.link
      ol
        - image.errors.full_messages.each do |error|
          li = error

= simple_form_for :image, url: add_images_path do |f|
  = f.input :text, as: :text, label: false, input_html: { class: "input-lg textarea" }
  .col-xs-offset-5 = f.button :submit, 'Добавить', class: "btn btn-lg"

app/views/images/create.js.erb
<%- if @image.new_record? %>
$(".form").html("<%= j(render 'form') %>")
<%- else %>
window.create_alert("<%= @message %>")
<%- end %>

app/views/images/destroy.js.erb
slide_row($('.image-row[data-id="<%= @image.id %>"]'))

app/views/images/edit.html.slim
.form.padding-top == render 'form'

app/views/images/index.html.slim
- if admin?
  .radio.cnt
    .btn-group data-toggle="buttons"
      label.btn.active
        input.switch type="radio" name="options" autocomplete="off" checked="checked" data-href==images_path
        | Все картинки
      label.btn
        input.switch type="radio" name="options" autocomplete="off" data-href==images_path(published: false)
        | Ожидающие одобрения


.radio.cnt
  .btn-group data-toggle="buttons"
    label.btn.active
      input.switch type="radio" name="options" autocomplete="off" checked="checked" data-href==images_path
      | По дате
    label.btn
      input.switch type="radio" name="options" autocomplete="off" data-href==images_path(order: "rating")
      | По рейтингу
#pagination-content
  == render "images_table", images: @images

app/views/images/index.js.erb
$("#pagination-content").html('<%= j(render "images_table", images: @images) %>')
if ($(window).scrollTop() > 300) {
  $('html, body').animate({
      scrollTop: $("#pagination-content").offset().top
  }, 300);
}

app/views/images/new.html.slim
.form.padding-top == render 'form'

app/views/images/search.html.slim
h3.text-header ...на случай важных переговоров
br
= simple_form_for :image, url: search_images_path, remote: true, html: { method: "get" } do |f|
  = f.input :text, label: false, input_html: { class: "input-lg autocomplete", value: nil }, placeholder: "Например: #{@random.last.try(:text)}"

.wrap
  == render "images_search"

app/views/images/search.js.erb
$(".wrap").hide().html('<%= j(render("images_search")) %>').fadeIn("normal");
init_clipboard_copy();

app/views/images/show.html.slim
= image_tag @image.link

app/views/images/unknown.html.slim
h3.text-header ...на случай важных переговоров
br
h3.gray.cnt Каждый раз рандомная:
.random.cnt
  - url = random_images_url(:n => Time.now.to_i)
  br
  p
    span#random-url.gray.copy data-clipboard-text==url data-timer==Time.now.to_i data-original-url==random_images_url = url
  br
  small Hint: можно добавлять в конец любую цифру или букву, чтобы картинки не кешировались

app/views/layouts/application.html.slim
doctype html
html lang="ru"
  head
    meta charset="utf-8"
    meta content="IE=edge" http-equiv="X-UA-Compatible"
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    meta content="Коллекция скриншотов из самой лучшей социальной сети. На случай важных переговоров." name="description"
    meta content="Vizakenjack" name="author"
    meta property="og:title" content="Это обман, чтобы набрать классы))000"
    meta property="og:locale" content="ru_RU"
    meta property="og:description" content="Скриншоты на случай важных переговоров."
    meta property="og:image" content==asset_path('icon.png')
    title = title_for_output
    = stylesheet_link_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", media: 'all', "data-turbolinks-track" => true
    = javascript_include_tag "//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js", media: 'all', "data-turbolinks-track" => true
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
      
    = csrf_meta_tags
    = favicon_link_tag 'icon.png', :rel => 'shortcut icon'
  body
    .container-fluid
        - if Rails.env.development?
          p.cnt DEV
        #nav.col-sm-12.col-md-8.col-md-offset-2.col-lg-6.col-lg-offset-3
          ul.list-unstyled
            = menu_item "index", link_to(fa_icon("list"), images_path, class: "btn btn-top")
            = menu_item "search", link_to(fa_icon("search"), search_images_path, class: "btn btn-top")
            = menu_item "unknown", link_to(fa_icon("random"), unknown_images_path, class: "btn btn-top")
            = menu_item "new", link_to(fa_icon("plus"), new_image_path, class: "btn btn-top")
    #main-content.container-fluid
      .col-sm-12.col-md-8.col-md-offset-2.col-lg-6.col-lg-offset-3
        .flash = bootstrap_flash
        #handy-alert
        = yield
    footer.footer
      .container.cnt
        p = footer_content
    - unless Rails.env.development?
      = render 'layouts/analytics'